name: tests
on:
  push:
    branches-ignore: [main]
  workflow_dispatch:

jobs:
  yarn-lockfile-check:
    uses: salesforcecli/github-workflows/.github/workflows/lockFileCheck.yml@main
  # Since the Windows unit tests take much longer, we run the linux unit tests first and then run the windows unit tests in parallel with NUTs
  linux-unit-tests:
    needs: yarn-lockfile-check
    uses: salesforcecli/github-workflows/.github/workflows/unitTestsLinux.yml@main
  windows-unit-tests:
    needs: linux-unit-tests
    uses: salesforcecli/github-workflows/.github/workflows/unitTestsWindows.yml@main
  nuts:
    needs: linux-unit-tests
    uses: salesforcecli/github-workflows/.github/workflows/nut.yml@main
    secrets: inherit
    strategy:
      matrix:
        # yes, macos.  oclif sometimes uses XDG, which also exists on gha/ubuntu, but isn't handled by testkit
        # see https://salesforce-internal.slack.com/archives/G02K6C90RBJ/p1669664263661369
        os: [windows-latest, macos-latest]
      fail-fast: false
    with:
      os: ${{ matrix.os }}
